server:
  port: 9296
  
spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sonukumar16/config-server
          # if configurations are in sub folders search the subfolder by below name
          #search-paths: server-config/